### ISSUE TITLE
Free version

### ISSUE THREAD

**Issue by rinka88** [templaza/templaza-framework#23]
Is it possible to use it to create your own template like Astroid?
If so, how to configure it?

**Comment by sonvnn** [comment]
Sure! The free template is a skeleton template. I created it to expand to other templates. You can use Two to create your own template.

1. Change the template name (xml, language file, template_name)
2. Add your extend style to create your own template style.

**Comment by rinka88** [comment]
does it work for wordpress? I'm not particularly good at WordPress, I'm looking for a template like in joomla)

**Comment by rinka88** [comment]
I installed it as written, it appeared in the plugins, but I couldn’t find the theme settings like in Astroid

**Comment by sonvnn** [comment]
What is the name of theme do you want to install?

**Comment by rinka88** [comment]
> What is the name of theme do you want to install?

doesn't work here like in joomla? installed and it comes with the theme? I would like a simple free theme and work on it like in joomla/ Astroid

**Comment by sonvnn** [comment]
So you can use Astroid instead of it :)

**Comment by rinka88** [comment]
but I have a website on WordPress😞 If it were joomla, then it would always be Astroid. And if there was a normal migrator from WordPress to Joomla, it would immediately migrate.

**Comment by rinka88** [comment]
It turns out there are no free themes to install and activate the plugin, and work on it like in Astroid?
